### ISSUE TITLE
Credit

### ISSUE THREAD

**Issue by JeremyWildsmith** [biesigrr/pe-loader#1]
Hey,

So I noticed this code is strikingly similar to my work here:
https://github.com/JeremyWildsmith/PELoader/blob/master/PeLoader.cpp

I really don't mind, but if this is based off of my work it would be nice if you mentioned it.

Also, the original code was distributed under GNU GPL; but I am open to re-license it to MIT.

Thanks,

Jeremy.

**Comment by biesigrr** [comment]
I've updated the README to correctly attribute you and link to your repository.

**Comment by JeremyWildsmith** [comment]
Cheers. Also for the record, I approve of this being MIT licensed. Thanks!

**Comment by biesigrr** [comment]
Cool, thanks. Also thank you for reminding me to put proper credits.
